packages:
  addressable_lambda_refresh: !include addressable_lambda_refresh.include.yaml

esphome:
  includes:
    - custom_addressable_lambdas.h

globals:
  - id: addressable_lambda_update_interval_ms
    type: const unsigned int
    restore_value: no
    initial_value: ${addressable_lambda_update_interval_ms}
  - id: addressable_lambda_update_frequency
    type: const float
    restore_value: no
    initial_value: 1000.0 / ${addressable_lambda_update_interval_ms}

number:
  - platform: template
    id: red_green_rainbow_speed
    name: Red-Green Rainbow Speed
    unit_of_measurement: s
    optimistic: true
    min_value: 0.5
    max_value: 60
    step: 0.5
    initial_value: 10
    restore_value: true
    mode: box
  - platform: template
    id: red_green_rainbow_direction_switch_interval
    name: Red-Green Rainbow Direction Switch Interval (0 means no switch)
    unit_of_measurement: s
    optimistic: true
    min_value: 0
    max_value: 3600
    step: 10
    initial_value: 0
    restore_value: true
    mode: box
  - platform: template
    id: red_green_twinkle_update_average
    name: Red-Green Twinkle Update Average (per pixel)
    unit_of_measurement: s
    optimistic: true
    min_value: 1
    max_value: 60
    step: 1
    initial_value: 20
    restore_value: true
    mode: box
  - platform: template
    id: red_green_rainbow_twinkle_cycle_interval
    name: Red-Green Rainbow/Twinkle Interval
    unit_of_measurement: s
    optimistic: true
    min_value: 10
    max_value: 3600
    step: 10
    initial_value: 60
    restore_value: true
    mode: box

select:
  - platform: template
    id: red_green_rainbow_direction
    name: Red-Green Rainbow Direction
    optimistic: true
    restore_value: true
    options:
      - forward
      - reverse
    initial_option: forward
